export const IA_MASTER_PRICE = "25\u202f000 FCFA";

export const IA_MASTER_MODULES = [
  {
    id: "01",
    title: "Fondamentaux de l'IA Générative & LLMs",
    level: "Débutant",
    summary: "Comprendre comment fonctionnent les modèles de langage, leurs architectures et leurs limites pour mieux les exploiter.",
    bullets: [
      "Histoire de l'IA : de Turing aux Transformers",
      "Architecture des LLMs : tokens, embeddings, attention, contexte",
      "Les grands modèles : GPT-5, Claude 3.5/4, Gemini 2.0, Mistral, LLaMA",
      "Benchmarks et évaluation des modèles (MMLU, HumanEval, Arena)",
      "Paramètres clés : température, top-p, max tokens, system prompts",
      "Prompt Engineering : zero-shot, few-shot, chain-of-thought, tree-of-thought",
      "RAG (Retrieval Augmented Generation) : principe et cas d'usage",
      "Fine-tuning vs prompting : quand et comment fine-tuner un modèle",
    ],
    project: "Créer un assistant expert personnalisé",
  },
  {
    id: "02",
    title: "IA Multimodale — Images & Vision",
    level: "Intermédiaire",
    summary: "Exploiter la génération et l'analyse d'images par l'IA pour des usages créatifs et professionnels.",
    bullets: [
      "Comprendre les modèles de diffusion : Stable Diffusion, Midjourney, Yanola AI…",
      "Techniques de prompting visuel : style, composition, éclairage, référence d'image",
      "ControlNet, IP-Adapter, LoRA : contrôle avancé de la génération",
      "Vision par l'IA : GPT-4o Vision, Claude Vision, Gemini Vision",
      "OCR intelligent et extraction d'informations depuis des documents/images",
      "Upscaling, inpainting, outpainting : retouche IA avancée",
      "Cas d'usage métier : marketing, design produit, e-commerce, médias",
    ],
    project: "Pipeline de génération d'assets visuels automatisé",
  },
  {
    id: "03",
    title: "IA Multimodale — Audio, Voix & Musique",
    level: "Intermédiaire",
    summary: "Maîtriser la génération, transcription et transformation audio par l'IA.",
    bullets: [
      "Speech-to-Text : Whisper (OpenAI), AssemblyAI — précision et usage",
      "Text-to-Speech : ElevenLabs — clonage vocal IA",
      "Génération musicale : Stable Audio",
      "Voice Agents : créer des assistants vocaux interactifs en temps réel",
      "Traitement audio IA : débruitage, séparation de stems, amélioration qualité",
      "Podcasts et contenus audio automatisés avec IA",
      "Real-time Voice API : intégration dans des applications",
      "Éthique et deepfakes audio : détection et réglementation",
    ],
    project: "Créer un podcast entièrement généré par IA",
  },
  {
    id: "04",
    title: "IA Multimodale — Vidéo",
    level: "Avancé",
    summary: "Générer, éditer et analyser des vidéos avec les derniers modèles IA.",
    bullets: [
      "Génération vidéo : Sora, Yanola AI",
      "Text-to-Video : techniques de prompting et de contrôle",
      "Image-to-Video et Video-to-Video : animation et transformation",
      "Avatars vidéo IA : HeyGen, Synthesia, D-ID — créer des présentateurs IA",
      "Lip sync et synchronisation labiale avec IA",
      "Édition vidéo assistée par IA : CapCut IA, Descript",
      "Analyse et compréhension vidéo par les VLMs (Video-Language Models)",
      "Workflows de production vidéo entièrement automatisés",
    ],
    project: "Produire une vidéo marketing de A à Z avec IA",
  },
  {
    id: "05",
    title: "Agents IA & Automatisation Intelligente",
    level: "Avancé",
    summary: "Concevoir des agents IA autonomes capables de raisonner, planifier et agir dans le monde réel.",
    bullets: [
      "Qu'est-ce qu'un agent IA ? Architecture ReAct, Plan-and-Execute, reflexion",
      "Mémoire des agents : mémoire à court terme, long terme, vectorielle",
      "Outils et actions : web browsing, code execution, API calls, file management",
      "Multi-agents : orchestration, communication et collaboration entre agents",
      "Agents no-code : n8n, Make, Lang Graph, OpenAI",
      "Computer Use : agents qui contrôlent un ordinateur (Claude, Operator GPT)",
      "Gestion des erreurs, boucles et hallucinations dans les agents",
    ],
    project: "Agent de recherche et synthèse de marché autonome",
  },
  {
    id: "06",
    title: "MCP — Model Context Protocol",
    level: "Avancé",
    summary: "Maîtriser le protocole MCP d'Anthropic pour connecter l'IA à n'importe quel outil et système.",
    bullets: [
      "Comprendre MCP : architecture client-serveur, stdio vs SSE vs HTTP",
      "Pourquoi MCP remplace les plugins et les function calls classiques",
      "Installer et configurer un serveur MCP : Claude Desktop, Cursor, Windsurf",
      "MCP Servers existants : filesystem, GitHub, Slack, Notion, Postgres, Brave Search…",
      "Créer son propre serveur MCP en Python ou TypeScript",
      "MCP Resources, Tools et Prompts : les 3 primitives à maîtriser",
      "Sécurité et authentification dans l'écosystème MCP",
      "MCP avec des agents multi-modèles : interopérabilité Claude + GPT + autres",
    ],
    project: "Construire un serveur MCP connecté à une base de données métier",
  },
  {
    id: "07",
    title: "Développement IA No-Code & Low-Code",
    level: "Intermédiaire",
    summary: "Construire des applications IA puissantes sans être développeur, en exploitant les meilleurs outils no-code.",
    bullets: [
      "Panorama des plateformes no-code IA : Bubble, Glide, Flutter Löw + IA",
      "Flowise et LangFlow : construire des pipelines LLM visuellement",
      "n8n et Make : automatiser avec l'IA (100+ intégrations)",
      "Duo : chatbots et voice bots avancés",
      "Créer des RAG apps sans code : upload de documents + chatbot",
      "Déploiement et partage d'apps IA : Vercel",
    ],
    project: "Créer une app IA complète en 3h sans code",
  },
  {
    id: "08",
    title: "Développement IA avec Code (Python & APIs)",
    level: "Avancé",
    summary: "Coder des applications IA robustes en Python en utilisant les APIs des grands modèles.",
    bullets: [
      "APIs OpenAI, Anthropic, Google, Mistral : authentification et bonnes pratiques",
      "LangChain : Framework de référence pour apps LLM",
      "Bases de données vectorielles : Pinecone",
      "Streaming, async et gestion de la latence dans les apps IA",
      "Function calling et structured outputs : extraire des données structurées",
      "Évaluation et monitoring : LangSmith",
      "Sécurité des LLMs : prompt injection, jailbreaks, guardrails",
    ],
    project: "API backend IA avec RAG et streaming en production",
  },
  {
    id: "09",
    title: "Applications IA Métier & Cas d'Usage Sectoriels",
    level: "Tous niveaux",
    summary: "Identifier et implémenter les cas d'usage IA les plus impactants selon les secteurs d'activité.",
    bullets: [
      "IA pour le Marketing : copywriting, SEO, social media, publicité personnalisée",
      "IA pour la Productivité : Notion IA, Microsoft Copilot, …",
      "IA pour le Coding : Cursor, GitHub Copilot, Claude Code",
      "IA pour la Juridique & Finance : analyse de contrats, due diligence, conformité",
      "IA pour la Santé : diagnostic assisté, synthèse médicale, drug discovery",
      "IA pour l'Éducation : tutorat personnalisé, création de cours, évaluation",
      "IA pour le Service Client : chatbots avancés, analyse sentiment, routing intelligent",
      "Construire un business case IA : ROI, coûts, risques, gouvernance",
    ],
    project: "Analyser et automatiser un processus métier réel avec IA",
  },
  {
    id: "10",
    title: "IA Responsable, Tendances & Stratégie Future",
    level: "Tous niveaux",
    summary: "Naviguer l'avenir de l'IA avec discernement : éthique, réglementation, veille technologique et positionnement stratégique.",
    bullets: [
      "Frontières de l'IA en 2025-2026 : reasoning models, o1/o3, Gemini 2.0 Flash Thinking",
      "IA AGI et au-delà : définitions, timelines et implications selon les experts",
      "Réglementation : EU AI Act, RGPD & IA, cadres de conformité à connaître",
      "Biais algorithmiques, équité et explicabilité des modèles (XAI)",
      "Droits d'auteur et propriété intellectuelle dans l'IA générative",
      "Empreinte carbone de l'IA et enjeux environnementaux",
      "Méthodes de veille IA : Twitter/X, Hugging Face, ArXiv, newsletters clés",
      "Construire sa roadmap personnelle de montée en compétences IA",
    ],
    project: "Présentation d'un projet IA complet devant jury",
  },
] as const;

export type IaMasterModule = (typeof IA_MASTER_MODULES)[number];

export const IA_MASTER_PARCOURS = [
  {
    id: "1",
    title: "L'Explorateur IA",
    who: "Pour les non-techniciens souhaitant adopter l'IA dans leur quotidien professionnel. Idéal pour les managers, commerciaux, RH et toute personne sans background technique.",
    modules: ["01", "07", "09", "10", "02", "03"],
    duration: "36 heures — 6 semaines (2 sessions/semaine)",
    outcome: "Utilisation experte des outils IA, automatisation des tâches sans code",
  },
  {
    id: "2",
    title: "Le Créateur IA",
    who: "Pour les professionnels du contenu, design et communication. Créatifs, marketers, social media managers, community managers et journalistes.",
    modules: ["01", "02", "03", "04", "07", "09"],
    duration: "36 heures — 6 semaines (2 sessions/semaine)",
    outcome: "Production de contenu multimédia complet avec IA, réduction des coûts de production",
  },
  {
    id: "3",
    title: "Le Builder IA",
    who: "Pour les développeurs et profils tech souhaitant intégrer l'IA dans leurs projets. Idéal pour les ingénieurs logiciels, data scientists et DevOps.",
    modules: ["01", "05", "06", "08", "09", "10"],
    duration: "36 heures — 6 semaines (2 sessions/semaine)",
    outcome: "Applications IA production-ready, agents autonomes, intégrations MCP",
  },
  {
    id: "4",
    title: "Le Stratège IA",
    who: "Pour les dirigeants, chefs de projet et consultants qui pilotent la transformation IA de leur organisation. Accent sur la stratégie, le ROI et la réglementation.",
    modules: ["01", "09", "10", "07", "05", "03"],
    duration: "36 heures — 6 semaines (2 sessions/semaine)",
    outcome: "Pilotage de la transformation IA, business cases, gouvernance et conformité",
  },
  {
    id: "5",
    title: "L'Entrepreneur IA",
    who: "Pour les fondateurs de startups, freelances et intrapreneurs qui veulent lancer un produit ou service basé sur l'IA. Accent sur la mise en marché et la construction rapide.",
    modules: ["01", "07", "05", "09", "10", "02"],
    duration: "36 heures — 6 semaines (2 sessions/semaine)",
    outcome: "Lancement rapide d'un produit ou service IA, time-to-market optimisé",
  },
  {
    id: "6",
    title: "AI MASTER Complet",
    who: "La formation complète pour devenir une référence en IA. Tous les modules. Pour ceux qui veulent couvrir l'intégralité de l'écosystème et se positionner comme expert ou consultant IA.",
    modules: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"],
    duration: "120 heures — 5 mois intensif (ou 10 mois standard)",
    outcome: "Maîtrise complète de l'écosystème IA, capacité de consulting et de leadership IA",
  },
] as const;

export type IaMasterParcours = (typeof IA_MASTER_PARCOURS)[number];

