export const DATA_MASTER_MODULES = [
  {
    id: "01",
    title: "Excel Avancé & Power Query",
    level: "Débutant",
    summary:
      "Passer d'un utilisateur basique à un analyste autonome : formules puissantes, tableaux croisés dynamiques maîtrisés et automatisation du nettoyage de données avec Power Query.",
    bullets: [
      "Architecture d'un fichier data : tables structurées, nommage, typage",
      "Fonctions clés pro : INDEX/MATCH, XLOOKUP, SUMIFS, IFERROR",
      "Philosophie Power Query : ETL visuel, steps reproductibles",
      "Erreurs fréquentes dans les TCD et leur correction",
      "Versionning manuel et documentation d'un fichier partagé",
      "Quand utiliser Excel vs Power BI : critères de décision",
      "Construire 12 formules avancées sur un dataset de ventes réelles",
      "TCD multi-sources avec segments et chronologie interactive",
      "Pipeline Power Query complet : 3 sources → nettoyage → table consolidée",
      "Audit guidé : corriger 5 fichiers Excel volontairement mal structurés",
      "Macro VBA simple : automatiser un rapport hebdomadaire en 1 clic",
      "Dashboard de suivi commercial prêt à envoyer à un manager",
    ],
    project:
      "Tableau de bord commercial multi-sources actualisable en 1 clic, documenté et partageable",
  },
  {
    id: "02",
    title: "Power BI — Modélisation & Rapports Professionnels",
    level: "Débutant",
    summary: "Créer des rapports Power BI bien modélisés, avec des mesures DAX solides, prêts à être publiés et partagés en entreprise.",
    bullets: [
      "Architecture Power BI : Desktop, Service, Mobile — rôles de chaque couche",
      "Modèle en étoile : pourquoi c'est fondamental et comment le construire",
      "DAX : contexte de ligne vs contexte de filtre — la distinction qui change tout",
      "Mesures vs colonnes calculées : règle d'or et cas d'usage de chaque",
      "Gouvernance basique : workspaces, rôles, partage sécurisé sur le Service",
      "Performance : colonnes inutiles, cardinalité haute, bonnes habitudes dès le début",
      "Construire un modèle en étoile depuis des fichiers CSV bruts (5 tables)",
      "Écrire 10 mesures DAX fondamentales (SUM, CALCULATE, FILTER, DIVIDE...)",
      "Dashboard RH : effectifs, absentéisme, turnover avec slicers dynamiques",
      "Dashboard financier : budget vs réalisé, variances, drill-through par département",
      "Publier sur Power BI Service et programmer l'actualisation automatique",
      "Critiquer et corriger 2 dashboards mal conçus fournis en atelier",
    ],
    project:
      "Dashboard d'activité complet publié sur Power BI Service avec accès sécurisé par département",
  },
  {
    id: "03",
    title: "Data Viz Excel & Power BI — Communiquer par la donnée",
    level: "Débutant",
    summary:
      "Produire des visualisations lisibles, honnêtes et efficaces. Savoir choisir le bon graphique et concevoir des dashboards que les décideurs comprennent du premier coup.",
    bullets: [
      "Grammaire des graphiques : chaque type de viz et son message naturel",
      "Préattention visuelle : couleur, taille, position — ce que l'oeil voit en premier",
      "Les 10 graphiques les plus trompeurs et pourquoi les éviter",
      "Principes de design : hiérarchie, alignement, espace blanc, contraste",
      "Adapter la viz au public : opérationnel, management, direction",
      "Accessibilité : palettes daltonisme-friendly, alternatives textuelles",
      "Recréer 8 graphiques Excel mal conçus en appliquant les principes vus",
      "Construire une palette de couleurs cohérente et l'appliquer sur Power BI",
      "Dashboard exécutif 1 page : une idée principale, lisible en 10 secondes",
      "Transformer un tableau croisé de 50 colonnes en 3 visualisations claires",
      "Concevoir un rapport Power BI mobile-friendly pour équipes terrain",
      "Présenter 2 viz devant le groupe et recevoir un feedback structuré",
    ],
    project:
      "Rapport de synthèse direction : 3 visualisations clés sur un problème métier réel, défendues à l'oral",
  },
  {
    id: "04",
    title: "Tableaux de Bord Avancés & Automatisation Excel/Power BI",
    level: "Débutant",
    summary:
      "Aller plus loin : Power BI avancé pour débutants, DAX intermédiaires, connecteurs et automatisation via Power Automate.",
    bullets: [
      "Time intelligence DAX : YTD, MTD, comparaisons N-1 — logique complète",
      "Row-Level Security (RLS) : sécuriser un rapport par utilisateur",
      "Power Automate : déclencher une action depuis Power BI (alertes, exports)",
      "Connecteurs Power BI : SharePoint, Teams, Google Analytics, Salesforce",
      "KPIs et objectifs : scorecards, indicateurs de performance lisibles",
      "Cycle de vie d'un rapport : recueil du besoin → livraison → maintenance",
      "Mesures time intelligence : CA mois, CA même période N-1, évolution %",
      "Configurer RLS dynamique sur un rapport multi-régions",
      "Connecter Power BI à SharePoint et programmer l'actualisation automatique",
      "Créer une alerte email automatique quand un KPI passe sous un seuil",
      "Scorecard de performance avec objectifs et couleurs conditionnelles",
      "Livrer un rapport complet à un client fictif avec documentation utilisateur",
    ],
    project:
      "Solution Power BI complète avec RLS, time intelligence, actualisation automatique et alerte Power Automate",
  },
  {
    id: "05",
    title: "SQL — Interroger et Analyser des Bases de Données",
    level: "Intermédiaire",
    summary:
      "Extraire, filtrer, agréger et analyser des données directement depuis des bases relationnelles. SQL est la compétence la plus demandée par les employeurs data.",
    bullets: [
      "Modèle relationnel : tables, clés, jointures — comprendre le schéma avant d'écrire",
      "NULL : comportement contre-intuitif, pièges et gestion correcte",
      "Fonctions de fenêtrage : ROW_NUMBER, RANK, LEAD/LAG — logique et cas d'usage",
      "Performance : lire un plan d'exécution, index, colonnes projetées seulement",
      "CTEs vs sous-requêtes : lisibilité, maintenabilité, quand choisir",
      "Conventions professionnelles : nommage, commentaires, requêtes lisibles par une équipe",
      "30 requêtes progressives sur une base e-commerce réelle (commandes, clients, produits)",
      "Analyser les ventes par segment et période avec GROUP BY + fonctions de fenêtrage",
      "Détecter doublons, valeurs aberrantes et anomalies dans un dataset de 200 000 lignes",
      "Réécrire 5 sous-requêtes imbriquées en CTEs lisibles et documentées",
      "Optimiser 3 requêtes lentes : avant/après avec plan d'exécution commenté",
      "Connecter la base SQL à Power BI et créer un rapport actualisé automatiquement",
    ],
    project:
      "Analyse complète d'une base de données PME fictive : 8 tables, 50 000 lignes, livrée avec documentation SQL",
  },
  {
    id: "06",
    title: "Python & Pandas — Analyse de Données Professionnelle",
    level: "Intermédiaire",
    summary:
      "Analyser, nettoyer et transformer des données avec Python. Pandas est l'outil standard du Data Analyst dans toutes les grandes organisations.",
    bullets: [
      "Environnements Python : Jupyter, Google Colab, venv — bonnes pratiques",
      "Pandas : indexing, .loc vs .iloc, chaîne de méthodes lisible et maintenable",
      "Valeurs manquantes : MCAR, MAR, MNAR — choisir l'imputation adaptée",
      "Performance Pandas : dtypes corrects, vectorisation, éviter les boucles",
      "Reproductibilité : seeds, pipelines déterministes, documentation du notebook",
      "Conventions Python data : PEP8, docstrings, code reviewable par une équipe",
      "Importer et inspecter un dataset de 300 000 lignes sans faire planter le kernel",
      "Pipeline de nettoyage réutilisable : types, manquants, doublons, outliers (IQR)",
      "Groupby, merge, pivot, melt : 15 transformations sur des données réelles",
      "Analyse exploratoire complète avec checklist professionnel (EDA structuré)",
      "Exporter les résultats en Excel multi-onglets, CSV et directement dans Power BI",
      "Notebook structuré et commenté prêt à être partagé et relu par un collègue",
    ],
    project:
      "Analyse exploratoire complète d'un dataset Open Data africain (économie ou santé) livrée en notebook documenté",
  },
  {
    id: "07",
    title: "Data Viz Python & Tableau — Storytelling Analytique",
    level: "Intermédiaire",
    summary:
      "Produire des visualisations analytiques de haut niveau avec Python (Matplotlib, Seaborn, Plotly) et Tableau, et maîtriser le storytelling par la donnée.",
    bullets: [
      "Choisir entre Matplotlib, Seaborn, Plotly, Altair et Tableau selon le contexte",
      "Encodings visuels avancés : position, taille, couleur, forme — hiérarchie d'efficacité",
      "LOD Tableau (FIXED, INCLUDE, EXCLUDE) : logique et erreurs classiques",
      "Structure narrative d'une analyse : intro → tension → insight → recommandation",
      "Storytelling pour non-data : simplifier sans trahir, vulgariser sans mentir",
      "Recréer 6 graphiques Python mal construits en les corrigeant avec les principes",
      "Rapport HTML interactif avec Plotly : 8 graphiques liés sur un cas métier",
      "Dashboard Tableau avec LOD : parts de marché par territoire et période",
      "Story Tableau 5 slides : présentation direction sur un problème réel",
      "Comparer Power BI vs Tableau vs Python sur un même problème : forces et limites",
      "Présenter une analyse de données devant le groupe en 8 minutes chrono",
      "Daltonisme et accessibilité : palettes sûres, test de contraste, alternatives",
    ],
    project:
      "Story data complète présentée comme un rapport direction : insight principal, 3 visualisations clés, recommandation chiffrée",
  },
  {
    id: "08",
    title: "Machine Learning Discriminatif — Classification & Régression",
    level: "Avancé",
    summary:
      "Comprendre, appliquer et évaluer les algorithmes de machine learning supervisé sur des problèmes métier concrets, avec la rigueur scientifique nécessaire à la production.",
    bullets: [
      "Biais-variance : comprendre le surapprentissage et sous-apprentissage en profondeur",
      "Data leakage : causes, détection et prévention — l'erreur la plus coûteuse en ML",
      "Validation croisée : stratified k-fold, time-series split, group k-fold",
      "Métriques : accuracy, precision, recall, F1, ROC-AUC, RMSE — coût métier des erreurs",
      "Interprétabilité : SHAP, importance des features, expliquer un modèle à un dirigeant",
      "Éthique ML : biais algorithmiques, équité, audit avant mise en production",
      "Détecter et corriger 4 cas de data leakage dans des notebooks existants",
      "Comparer 5 algorithmes (régression logistique, random forest, XGBoost, SVM, KNN) sur un dataset réel",
      "Pipeline Scikit-learn complet : preprocessing → modèle → évaluation → export",
      "Expliquer un modèle Black Box avec SHAP : rapport de 3 slides pour un CODIR",
      "Modèle de prédiction du churn client : de la donnée brute à la liste de clients à risque",
      "Audit de fairness : détecter un biais dans un modèle de scoring de crédit",
    ],
    project:
      "Modèle de prédiction du churn client : données brutes → pipeline → évaluation → rapport d'interprétation livré",
  },
  {
    id: "09",
    title: "Pipelines de Données — Orchestration & Architecture",
    level: "Avancé",
    summary:
      "Concevoir des pipelines de données de production : orchestration, architecture moderne (Medallion/Lakehouse) et qualité des données à l'échelle.",
    bullets: [
      "Architecture data moderne : Medallion (Bronze/Silver/Gold), Lakehouse vs Data Warehouse",
      "Idempotence : pourquoi c'est non négociable dans un pipeline de production",
      "Apache Airflow : DAGs, tasks, scheduling, retry, SLAs, alertes — architecture complète",
      "Qualité des données en pipeline : validation automatique, alertes, logs structurés",
      "dbt : modélisation SQL versionnée, tests, documentation, lineage",
      "Quand utiliser Python, SQL, dbt ou Airflow : règles de décision professionnelles",
      "Construire un DAG Airflow complet : ingestion → nettoyage → chargement → alerte Slack",
      "Pipeline idempotent : tester qu'une relance ne crée pas de doublons",
      "Projet dbt complet : staging → intermediate → mart avec tests et documentation",
      "Pipeline BigQuery : CSV brut → tables Gold → dashboard Power BI actualisé",
      "Simuler une panne et analyser les logs pour identifier et corriger l'incident",
      "Post-mortem d'un pipeline défaillant : rapport et plan correctif structuré",
    ],
    project:
      "Pipeline ELT complet : ingestion multi-source → Medallion sur BigQuery → dashboard Power BI avec orchestration Airflow",
  },
  {
    id: "10",
    title: "SQL Avancé & Gouvernance Data",
    level: "Avancé",
    summary:
      "Maîtriser les requêtes analytiques complexes, l'optimisation sur entrepôts cloud et la gouvernance des données pour des environnements de production en équipe.",
    bullets: [
      "Fenêtres analytiques avancées : frames, NTILE, PERCENT_RANK, CUME_DIST",
      "Optimisation cloud : partitionnement, clustering, coût des requêtes BigQuery/Snowflake",
      "Data contracts : définir et faire respecter les engagements entre producteurs et consommateurs",
      "Réécrire 8 requêtes analytiques complexes en CTEs documentées et testées",
      "Optimiser un pipeline BigQuery : réduire le coût de 40 % avec partitionnement et clustering",
      "Déployer un projet dbt avec CI/CD : tests automatiques à chaque merge",
      "Configurer RLS dynamique et column masking sur un schéma multi-tenant",
      "Gouvernance : data catalog, data lineage, qualité des données à l'échelle",
      "RGPD appliqué : anonymisation, pseudonymisation, rétention, Privacy by Design",
      "Sécurité SQL : row-level security, column masking, audit logs, migrations",
      "Auditer la conformité RGPD d'un dataset : rapport avec plan de remédiation",
      "Construire un mini data catalog sur 3 tables critiques d'une organisation fictive",
    ],
    project: "Pipeline SQL production-ready sur BigQuery avec dbt, CI/CD, RLS, audit RGPD et documentation data catalog",
  },
] as const;

export type DataMasterModule = (typeof DATA_MASTER_MODULES)[number];

export const DATA_MASTER_PARCOURS = [
  {
    id: "1",
    title: "L'Analyste Data",
    who: "Pour les profils non-tech qui travaillent déjà avec des données : contrôleurs de gestion, chargés de reporting, assistants commerciaux et RH. Zéro programmation, 100 % applicable dès le lendemain.",
    modules: ["01", "02", "03", "04", "05", "07"],
    duration: "54 heures — 9 semaine",
    rhythm: "2 sessions de 3h par semaine",
    outcome: "Excel, Tableau de bord, SQL fluide, reporting autonome et actualisable",
  },
  {
    id: "2",
    title: "Le Data Analyst Python",
    who: "Pour les profils ayant déjà une base en Excel/SQL et souhaitant ajouter Python à leur boîte à outils. Accent sur l'analyse reproductible, l'automatisation et la visualisation avancée.",
    modules: ["01", "05", "06", "07", "02", "03"],
    duration: "54 heures — 9 semaine",
    rhythm: "2 sessions de 3h par semaine",
    outcome: "Analyses Python documentées et reproductibles, dashboards Tableau et Power BI, SQL Cloud",
  },
  {
    id: "3",
    title: "Le Data Scientist",
    who: "Pour les profils maîtrisant Python et SQL et souhaitant construire des modèles prédictifs rigoureux et les déployer. Accent sur la rigueur scientifique et la mise en production.",
    modules: ["06", "05", "10", "08", "09", "07"],
    duration: "54 heures — 9 semaine",
    rhythm: "2 sessions de 3h par semaine",
    outcome: "Modèles ML supervisés déployés, pipelines automatisés, audit d'équité et interprétabilité",
  },
  {
    id: "4",
    title: "Le Data Engineer",
    who: "Pour les développeurs et ingénieurs qui veulent construire des infrastructures de données robustes, orchestrées et maintenues en équipe avec les standards de l'industrie.",
    modules: ["05", "10", "06", "09", "01", "02"],
    duration: "54 heures — 9 semaine",
    rhythm: "2 sessions de 3h par semaine",
    outcome: "Pipelines ELT idempotents, orchestration Airflow, architecture Medallion, gouvernance SQL",
  },
  {
    id: "5",
    title: "Le Stratège Data",
    who: "Pour les dirigeants, chefs de projet et managers qui pilotent la transformation data de leur organisation. Accent sur la compréhension des outils, la stratégie et la communication aux décideurs.",
    modules: ["01", "02", "03", "04", "07", "10"],
    duration: "54 heures — 9 semaine",
    rhythm: "2 sessions de 3h par semaine",
    outcome: "Dashboards exécutifs, RLS, automatisation, storytelling direction et gouvernance data",
  },
  {
    id: "6",
    title: "DATA MASTER Complet",
    who: "La formation intégrale pour maîtriser toute la chaîne de valeur de la donnée. Tous les niveaux, tous les outils. Pour devenir la référence data de son organisation ou se positionner comme consultant.",
    modules: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10"],
    duration: "160 heures — 6 mois",
    rhythm: "2 sessions de 3h par semaine",
    outcome: "Maîtrise complète : Excel, Power BI, SQL, Python, ML, pipelines et gouvernance data",
  },
] as const;

export type DataMasterParcours = (typeof DATA_MASTER_PARCOURS)[number];

